version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.10.2
    - 3.9.1
    - 4.0.0
    - 4.0.2
    - 4.0.3
    - 4.1.10
    - 4.1.2
    - 4.1.3
    - 4.1.5
    - 4.1.6
    - 4.1.8
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.33
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.12.0
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.1.1
    - 5.1.2
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.1.2
    - 13.1.5
  - dependency-name: jest-styled-components
    versions:
    - 7.0.4
  - dependency-name: cypress
    versions:
    - 7.1.0
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.4
    - 24.3.5
  - dependency-name: next
    versions:
    - 10.0.8
    - 10.1.1
    - 10.1.3
  - dependency-name: styled-components
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.1.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.1.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.6
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.17.0
    - 4.19.0
    - 4.20.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.17.0
    - 4.19.0
    - 4.20.0
  - dependency-name: "@xstyled/styled-components"
    versions:
    - 2.3.0
    - 2.4.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
    - 7.23.1
  - dependency-name: react-is
    versions:
    - 17.0.2
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: husky
    versions:
    - 5.1.3
    - 5.2.0
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.2.3
