const filterNames = [
  { name: '1977', filter: 'filter-1977' },
  { name: 'Aden', filter: 'filter-aden' },
  { name: 'Amaro', filter: 'filter-amaro' },
  { name: 'Ashby', filter: 'filter-ashby' },
  { name: 'Brannan', filter: 'filter-brannan' },
  { name: 'Brooklyn', filter: 'filter-brooklyn' },
  { name: 'Charmes', filter: 'filter-charmes' },
  { name: 'Clarendon', filter: 'filter-clarendon' },
  { name: 'Crema', filter: 'filter-crema' },
  { name: 'Dogpatch', filter: 'filter-dogpatch' },
  { name: 'Earlybird', filter: 'filter-earlybird' },
  { name: 'Gingham', filter: 'filter-gingham' },
  { name: 'Ginza', filter: 'filter-ginza' },
  { name: 'Hefe', filter: 'filter-hefe' },
  { name: 'Helena', filter: 'filter-helena' },
  { name: 'Hudson', filter: 'filter-hudson' },
  { name: 'Inkwell', filter: 'filter-inkwell' },
  { name: 'Kelvin', filter: 'filter-kelvin' },
  { name: 'Kuno', filter: 'filter-juno' },
  { name: 'Lark', filter: 'filter-lark' },
  { name: 'Lo-Fi', filter: 'filter-lofi' },
  { name: 'Ludwig', filter: 'filter-ludwig' },
  { name: 'Maven', filter: 'filter-maven' },
  { name: 'Mayfair', filter: 'filter-mayfair' },
  { name: 'Moon', filter: 'filter-moon' },
  { name: 'Nashville', filter: 'filter-nashville' },
  { name: 'Perpetua', filter: 'filter-perpetua' },
  { name: 'Poprocket', filter: 'filter-poprocket' },
  { name: 'Reyes', filter: 'filter-reyes' },
  { name: 'Rise', filter: 'filter-rise' },
  { name: 'Sierra', filter: 'filter-sierra' },
  { name: 'Skyline', filter: 'filter-skyline' },
  { name: 'Slumber', filter: 'filter-slumber' },
  { name: 'Stinson', filter: 'filter-stinson' },
  { name: 'Sutro', filter: 'filter-sutro' },
  { name: 'Toaster', filter: 'filter-toaster' },
  { name: 'Valencia', filter: 'filter-valencia' },
  { name: 'Vesper', filter: 'filter-vesper' },
  { name: 'Walden', filter: 'filter-walden' },
  { name: 'Willow', filter: 'filter-willow' },
  { name: 'X-Pro II', filter: 'filter-xpro-ii' }
]

export default filterNames
